TheFocusTech/DomainQA

fixtures.js
playwright.config.js
pom/pages/HomePage.js
pom/pages/LoginPage.js
testData.js
tests/02Authorization.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.rrgjsbcqig8c

TC_02_02 |  Verify user can login into their account without 2FA.

---

fixtures.js
pom/pages/SettingsGeneralPage.js
tests/08MyProfile.spec.js

RF_TC_08_02_02

---

.gitignore
testData.js
tests/01Registration.spec.js
tests/02Authorization.spec.js
tests/04Domains.spec.js
tests/08MyProfile.spec.js
tests/09NonAuthorizedUser.spec.js

RF Qase links
Add .idea/ to .gitignore

RF Qase links

---

pom/components/HeaderComponent.js
testData.js
tests/08MyProfile.spec.js

[TC_08_01 | Verify the Profile Dropdown Menu is displayed on "My Profile" Button Click
](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.gu0m5ch4yg2x)

My profile/tc 08 01/profile dropdown menu

---

fixtures.js
helpers/apiCalls.js
helpers/postconditions.js
pom/modalWindows/EnableDnssecModal.js
pom/pages/HostedZonesDetailPage.js
pom/pages/HostedZonesPage.js
testData.js
tests/04Domains.spec.js

[TC_04_08](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.lljlr5vp8gu)

TC_04_08 | Verify user can enable DNSSEC

---

pom/pages/SettingsGeneralPage.js
tests/08MyProfile.spec.js

Added 2 tests to change currency type:
1. from USD to EUR
2. from EUR to USD

My profile/General info TC 08 02 04

---

pom/pages/BlogPage.js
testData.js
tests/06Blog.spec.js

[TC_06_08 | Verify Autocomplete Suggestions Displayed for Partial Search Input](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.wu2onbnm0a9o)
[QASE Blog](https://app.qase.io/project/01?case=29&previewMode=side&suite=8&tab=)

feat: add test TC_06_08 autocomplete suggestions

---

helpers/apiCalls.js
tests/04Domains.spec.js
tests/07HelpCenter.spec.js

added 1s timeout between requests, improved logging

TC_04_02 - improvements

---

.env.example
tests/07HelpCenter.spec.js

1. Committed Timeout
2.  Add test.slow()
3. Changed env file
4. Skip unstable click in TC 07_01_01

TC_07_01_03 refactor: changed timeout

---

fixtures.js
pom/pages/SettingsGeneralPage.js
pom/pages/SettingsNotificationsPage.js
testData.js
tests/08MyProfile.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.333obp2smjp7
https://app.qase.io/project/01?case=15&suite=11

TC_08_04_01

---

pom/components/HeaderComponent.js
testData.js
tests/08MyProfile.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.w8we6didi3d6

TC_08_07 | Verify that the user can log out of the account from the Profile Menu

---

helpers/apiCalls.js
pom/pages/SignupPage.js
testData.js
tests/01Registration.spec.js

Also added api requests SignIn, GetVerificationCode, DeleteUser (если не нужно, я удалю)
[Qase](https://app.qase.io/case/01-1)
[ATC](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.y7nujkap1fcv)

 TC_01_01_01 | Verify Registration form elements

---

fixtures.js
helpers/utils.js
pom/modalWindows/AdvancedSearchModal.js
pom/pages/DomainAvailabilityPage.js
pom/pages/HomePage.js
tests/09NonAuthorizedUser.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.5vbs55mgoksg

TC_09_03_05 | Verify unauthorized user can select TLD in different categories and see relevant search results

---

pom/pages/ContactsPage.js
pom/pages/CreateContactPage.js
tests/01Registration.spec.js

Add additional assert and correct locator

RF TC_01_01_04 

---

pom/pages/DomainAvailabilityPage.js
testData.js
tests/09NonAuthorizedUser.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.cba4s4hsjfkn

TC_09_03_06 | Verify that user can select several TLDs and see relevant search results

---

pom/pages/SettingsGeneralPage.js
testData.js
tests/08MyProfile.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.i6ekc2w8f8ut
https://app.qase.io/project/01?case=13&suite=11

TC_08_02_01

---

helpers/apiCalls.js
index.js
pom/pages/ForgotPasswordPage.js
testData.js
tests/01Registration.spec.js
tests/09NonAuthorizedUser.spec.js

[ATC](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.9prb2gacbixm)

TC_09_05_03 | Verify password recovery process

---

testData.js
tests/09NonAuthorizedUser.spec.js

https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.d35uri5uazho
https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.q2w803gtufhx

fix testData TC_09_04_01 and TC_09_04_03

---

fixtures.js
pom/pages/HelpCategoryPage.js
pom/pages/HelpCenterPage.js
testData.js
tests/07HelpCenter.spec.js

[TC_07_02_01 | Verify the user can navigate through the Knowledge Base category](https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.nc1tclwhmwhq)

feat: add test TC_07_02_01 Navigating through the KnowledgeBase category

---

helpers/apiCalls.js
index.js
tests/02Authorization.spec.js
tests/06Blog.spec.js
tests/09NonAuthorizedUser.spec.js

- changed user to increase tests stability
- updated getVerificationCodeFromEmail (@ViktoriyaED thanks!)
- added delay before checking email
- removed 'resend code' step

TC_09_05_03 | Verify password recovery process - rf

---

pom/pages/BlogSearchResultsPage.js
tests/06Blog.spec.js
tests/09NonAuthorizedUser.spec.js

fix test 06_04 change locator

---

pom/pages/SslCertificatesPage.js
testData.js
tests/01Registration.spec.js
tests/09NonAuthorizedUser.spec.js

https://app.qase.io/case/01-18
https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.63m6yfip96dy

TC_09_04_02 | Verify unauthorised user will be redirected to the Login Page from SSL Сertificates Page

---

fixtures.js
package-lock.json
package.json
pom/pages/HelpContactUsPage.js
testData.js
tests/09NonAuthorizedUser.spec.js

[https://docs.google.com/document/d/1ff46TvvPYvH_AZfc4Ilqv6Dbo9Jxp31GQh-IJhrr0wc/edit?tab=t.0#heading=h.u35mzacv094r](TC)
add faker

TC_09_06 |  Verify unauthorized users can submit the 'Contact us' form with diff types

---

pom/pages/HelpCenterArticlePage.js
pom/pages/HelpSearchResultsPage.js
tests/07HelpCenter.spec.js

Edited Allure steps in TC_07_01_04, TC_07_01_05 and TC_07_01_06.

Help center/tc 07 01 04 verify search articles with valid query

---

index.js
pom/pages/CreateContactPage.js
tests/01Registration.spec.js

RF TC_01_01_03

---

pom/components/HeaderComponent.js

this should fix webkit run for the following tests:
- TC_08_06
- TC_03_01_01 - 10
- TC_03_02_01 - 03

Update currency related pom to pass in both chrome and webkit
